[package]
description = "Library wrapping the awesome PokeAPI"
documentation = "https://docs.rs/rustemon/latest/rustemon/"
edition = "2021"
homepage = "https://github.com/mlemesle/rustemon"
keywords = ["pokeapi", "pokemon", "wrapper", "http", "rest"]
license = "MIT"
name = "rustemon"
readme = "README.md"
repository = "https://github.com/mlemesle/rustemon"
version = "4.0.0"

[features]
serialize = []

[dependencies]
async-trait = "0.1.83"
http-cache-reqwest = { version = "0.15.0", features = ["manager-moka"] }
reqwest = { version = "0.12.9", features = ["json"] }
reqwest-middleware = "0.4.0"
serde = { version = "1.0.216", features = ["derive"] }
thiserror = "2.0.6"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
toml = "0.8"

[[example]]
name = "toml_serialize"
required-features = ["serialize"]
